FROM golang:alpine

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

RUN apk update
RUN apk add curl

RUN go get -u github.com/cosmtrek/air

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

COPY go.mod .
COPY go.sum .
RUN go mod download

CMD /wait && air -c .air.toml