CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  nickname VARCHAR(25) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  image_path TEXT NOT NULL,
  is_admin BOOL DEFAULT FALSE,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);