CREATE TABLE replies(
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  comment_id INTEGER NOT NULL REFERENCES comments(id)
  ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE
  CASCADE
);